FROM node:22

# Establecer directorio de trabajo dentro del contenedor
WORKDIR /app

# Crear directorio para los logs (importante para ELK)
RUN mkdir -p /var/log/backend && chmod 777 /var/log/backend

# Copiar package.json y package-lock.json (si existe)
COPY server/package*json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY server .

# Exponer el puerto que usa la aplicación
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["npm", "run", "dev"]