services:
  mongodb:
    image: mongo:7
    container_name: fisio_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fisio_network

  backend:
    build: 
      context: .
      dockerfile: docker/backend/dockerfile
    container_name: fisio_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/fisio
    networks:
      - fisio_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/dockerfile
    container_name: fisio_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - fisio_network

volumes:
  mongo_data:

networks:
 fisio_network: